version: 1
name: "Formulário de GMUD"
description: "Preencha os campos abaixo para enviar seu Pull Request."
title: "[GMUD] - "
labels:
  - gmud
body:
  - type: dropdown
    id: quebrar_sistema
    attributes:
      label: "Essa mudança pode quebrar o sistema?"
      options:
        - label: "Sim"
          value: "sim"
        - label: "Não"
          value: "nao"

  - type: textarea
    id: motivo
    attributes:
      label: "Caso a resposta acima for 'Sim', detalhe o motivo:"
      description: "Explique o motivo da mudança que pode quebrar o sistema."
      placeholder: "Digite o motivo..."

  - type: dropdown
    id: prioridade
    attributes:
      label: "Classifique a prioridade dessa mudança:"
      options:
        - label: "Crítica"
          value: "critica"
        - label: "N/A"
          value: "na"
        - label: "Normal"
          value: "normal"

  - type: dropdown
    id: testes
    attributes:
      label: "A mudança passou pelos testes automatizados?"
      options:
        - label: "Sim"
          value: "sim"
        - label: "Não"
          value: "nao"

  - type: dropdown
    id: homologado
    attributes:
      label: "A mudança foi homologada por QA?"
      options:
        - label: "Sim"
          value: "sim"
        - label: "Não"
          value: "nao"

  - type: markdown
    attributes:
      value: "Essa mudança terá alterações no banco de dados? (Será atualizado automaticamente)"
