name: Redirect Hotfix/Feature PR to Develop

on:
  pull_request:
    types: [opened]
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  redirect-pr:
    if: startsWith(github.event.pull_request.head.ref, 'hotfix') || startsWith(github.event.pull_request.head.ref, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Criar PR para develop
        id: create_pr
        uses: actions/github-script@v6
        with:
          script: |
            const originalPR = context.payload.pull_request;
            console.log("PR original #" + originalPR.number);
            // Cria o PR para develop usando o mesmo head branch,
            // definindo o corpo como apenas o link para o PR da main
            const newPR = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: originalPR.title,
              head: originalPR.head.ref,
              base: "develop",
              body: `Pull Request para Main: ${originalPR.html_url}`
            });
            core.setOutput("newPRUrl", newPR.data.html_url);
            core.setOutput("newPRNumber", newPR.data.number.toString());
            core.setOutput("originalPRUrl", originalPR.html_url);
            return JSON.stringify(newPR.data);

      - name: Comentar no PR original com link do PR para develop
        uses: actions/github-script@v6
        with:
          script: |
            const originalPR = context.payload.pull_request;
            const newPRUrl = '${{ steps.create_pr.outputs.newPRUrl }}';
            const commentBody = `Pull Request para Develop: ${newPRUrl}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: originalPR.number,
              body: commentBody
            });
            console.log("Comentário criado no PR original.");

      - name: Atualizar corpo do PR para develop (garantir que contém só o link)
        uses: actions/github-script@v6
        with:
          script: |
            const newPRNumber = parseInt('${{ steps.create_pr.outputs.newPRNumber }}', 10);
            const originalPRUrl = '${{ steps.create_pr.outputs.originalPRUrl }}';
            const newBody = `Pull Request para Main: ${originalPRUrl}`;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: newPRNumber,
              body: newBody
            });
            console.log("Corpo do PR para develop atualizado para conter somente o link.");
